server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
spring:
  application:
    name: client-app
